### ISSUE TITLE
Start menu

### ISSUE THREAD

**Issue by Zaelot** [Zaelot/Cultist-Meditation#1]
Apartment of the Initiate, choose goal. This is up to the host.
Goals:
- Map the Dungeon
- ~~Reach the bottom level (survive)~~
- Reach altar and make a sacrifice
- Populate dungeon (Reach summoning circle and perform ritual)
- Clear dungeon (Slay population)
- Bargain with the old ones (Reach bottom and make your pitch)

**Comment by stcl** [comment]
- Forward or die: Reach certain amount of forwards not going back
