### ISSUE TITLE
Control vote logic

### ISSUE THREAD

**Issue by stcl** [Zaelot/Cultist-Meditation#14]
- Every <timestep> a controlling vote is made based on average key value.
- If no keys are registered, a vote is made randomly

**Comment by Zaelot** [comment]
Just remember to add that timer! :)

**Comment by stcl** [comment]
Key presses are not shown, bot shows how many have voted after the turn

**Comment by Zaelot** [comment]
Probably need to avoid multiple votes by singe viewer as well.
