### ISSUE TITLE
Twitch API

### ISSUE THREAD

**Issue by Zaelot** [Zaelot/Cultist-Meditation#2]
From twitch to game
- Listen for votes  -- Done by Moobot
- Count votes -- Done by Moobot
- 30 seconds counter (if tied, pick at random from tied; if none, send random) -- Done by Moobot
- Send the result to game -- Done by listening via IRC protocol

From game to twitch:
- Listen to game (announcements etc)

**Comment by Domestus** [comment]
http://forum.unity3d.com/threads/irc-chat-unitypackage.68070/
^ irc chat plugin for unity

**Comment by Domestus** [comment]
https://github.com/Zaelot/Cultist-Meditation/pull/12
Uses https://github.com/Grahnz/TwitchIRC-Unity to connect via the IRC protocol to the Twitch chat room.

We can now start reading chat messages from specific user in the channel and do actions according to the chat messages we get.

**Comment by Domestus** [comment]
Use http://twitchapps.com/tmi/ to create the auth token for your own twitch user

**Comment by Zaelot** [comment]
The 30 seconds for voting was used in the twitch Plays Pokémon as well: https://en.wikipedia.org/wiki/Twitch_Plays_Pokémon
